export { default as dummy } from "./dummy.js";
export { default as brown_frog } from "./floor 1/frog lake/brown_frog.js";
export { default as evil_frog } from "./floor 1/frog lake/evil_frog.js";
export { default as green_frog } from "./floor 1/frog lake/green_frog.js";
export { default as milky_frog } from "./floor 1/frog lake/milky_frog.js";
export { default as baby_goblin } from "./floor 1/goblin caves/baby_goblin.js";
export { default as hobgoblin } from "./floor 1/goblin caves/hobgoblin.js";
export { default as hungry_goblin } from "./floor 1/goblin caves/hungry_goblin.js";
export { default as sentient_rock } from "./floor 1/goblin caves/sentient_rock.js";
export { default as big_slime } from "./floor 1/slime fields/big_slime.js";
export { default as burning_slime } from "./floor 1/slime fields/burning_slime.js";
export { default as small_slime } from "./floor 1/slime fields/small_slime.js";
export { default as wet_slime } from "./floor 1/slime fields/wet_slime.js";
